export const PlayerAnimations = {//IMPORTANT FIX ANIMATION DIRECTION SITUATION
    IDLE: "IDLE",
    WALK: "WALK",
    //WALK_LEFT: "WALKING_LEFT",
    //WALK_RIGHT: "WALKING_RIGHT",
    //SHOOT_LEFT: "WATERGUN_LEFT",
    //SHOOT_RIGHT: "WATERGUN_RIGHT",
    //DAMAGE_LEFT: "DAMAGE_LEFT",
    //DAMAGE_RIGHT: "DAMAGE_RIGHT",
    DAMAGE: "DAMAGE",
    DYING: "DYING",
    DEAD: "DEAD"
}